#!/usr/local/share/ruby1.8/bin/ruby
require 'rubygems'
require 'cgi'
require 'nokogiri'
require 'open-uri'  

class Iciba
  
  HOME_DIR = `echo $HOME`.delete "\n" 
  PRON_DIR = "#{HOME_DIR}/.iciba_pron_tmp"

  def initialize(word)
    @word = word
  end

  def search
    (@word =~ /[a-zA-Z]/).nil? ? search_cn : search_en
  end

  def search_en
    open("http://dict-co.iciba.com/api/dictionary.php?w=" + CGI::escape(@word)) { |http| @result = http.read }
    doc = Nokogiri::HTML(open("http://dict-co.iciba.com/api/dictionary.php?w=" + CGI::escape(@word)))
    puts doc.css("dict/key").text
    puts "[#{doc.css("dict/ps").text}]"
    doc.css("dict/pron").each do |e| 
      download_pron e.text 
      play_pron e.text.split("/").last
    end
    pos_array,acc_array = [],[]
    doc.css("dict/pos").each { |e| pos_array << e.text }
    doc.css("dict/acceptation").each { |e| acc_array << e.text }
    pos_array.each_index { |i| puts pos_array[i] + " " + acc_array[i] }
    pos_array.clear
    acc_array.clear
    doc.css("dict/sent/orig").each { |e| pos_array << e.text }
    doc.css("dict/sent/trans").each { |e| acc_array << e.text }
    pos_array.each_index { |i| puts "例句" + (i+1).to_s + "：" + pos_array[i] + " " + acc_array[i] }
  end

  def search_cn
    uri = URI.parse("http://www.iciba.com/" + CGI::escape(ARGV[0]))
    doc = Nokogiri::HTML(open(uri))
    doc.css("#sentence_close>.tab_content>.a_c_3").each { |item| puts item.text }
  end

  def download_pron url
    Dir.mkdir PRON_DIR unless File.directory? PRON_DIR
    `wget -q -P #{PRON_DIR} #{url}`        
  end

  def play_pron file_name
    `mpg123 #{PRON_DIR}/#{file_name}`
    `rm -rf #{PRON_DIR}`
  end
end

if ARGV[0]
  iciba = Iciba.new(ARGV[0])
  iciba.search
else
  puts "please add the word needed to search" unless ARGV[0]
end
