#!/usr/local/share/ruby1.8/bin/ruby
require 'rubygems'
require 'cgi'
require 'nokogiri'
require 'open-uri'
require 'colored'

class Iciba

  HOME_DIR = `echo $HOME`.delete "\n"
  PRON_DIR = "#{HOME_DIR}/.iciba_pron_tmp"

  def initialize(word)
    @word = word
    Dir.mkdir PRON_DIR unless File.directory? PRON_DIR
  end

  def search
    (@word =~ /[a-zA-Z]/).nil? ? search_cn : search_en
  end

  def search_en
    unless File.exist?("#{PRON_DIR}/#{@word}")
      file = File.open("#{PRON_DIR}/#{@word}","w")
      doc = Nokogiri::HTML(open("http://dict-co.iciba.com/api/dictionary.php?w=" + CGI::escape(@word)))
      file.puts doc.css("dict/key").text
      file.puts "[#{doc.css("dict/ps").text}]"
      doc.css("dict/pron").each { |e| download_pron e.text }
      pos_array,acc_array = [],[]
      doc.css("dict/pos").each { |e| pos_array << e.text }
      doc.css("dict/acceptation").each { |e| acc_array << e.text }
      pos_array.each_index { |i| file.puts pos_array[i] + " " + acc_array[i] }
      pos_array.clear
      acc_array.clear
      doc.css("dict/sent/orig").each { |e| pos_array << e.text }
      doc.css("dict/sent/trans").each { |e| acc_array << e.text }
      pos_array.each_index { |i| file.puts "例句" + (i+1).to_s + "：" + pos_array[i] + " " + acc_array[i] }
      file.close
    end
    File.open("#{PRON_DIR}/#{@word}","r") do |file|
      #Show Key
      puts file.gets.gsub("\n","").blue
      #Show Pron
      line = file.gets
      puts line.gsub("\n","").magenta if line.gsub("\n","") != "[]"
      #Show meaning
      puts file.gets.gsub("\n","").cyan
      odd_even = true
      while line=file.gets do
        color = odd_even ? "white" : "cyan"
        puts line.gsub("\n","").send(color)
        odd_even = !odd_even
      end
    end
    play_pron
  end

  def search_cn
    uri = URI.parse("http://www.iciba.com/" + CGI::escape(ARGV[0]))
    doc = Nokogiri::HTML(open(uri))
    doc.css("#sentence_close>.tab_content>.a_c_3").each { |item| puts item.text }
  end

  def download_pron url
    `wget -o #{PRON_DIR}/tmp #{url} -O #{PRON_DIR}/#{@word}.mp3`
  end

  def play_pron
    `mplayer #{PRON_DIR}/#{@word}.mp3 -really-quiet`
  end
end

if ARGV[0]
  iciba = Iciba.new(ARGV[0])
  iciba.search
else
  puts "please add the word needed to search" unless ARGV[0]
end
